---
- name: Copy backend compiled web server
  copy:
    src: /root/project/artifact.tar.gz 
    dest: /home/ubuntu
- name: extract backend files
  shell: |
    cd /home/ubuntu/
    tar xvf artifact.tar.gz

- name: Install node
  shell: |
    cd /home/ubuntu/
    npm install
    npm install
    pm2 stop default
    pm2 start npm -- start
# - name: Build Node
#   shell: |
#     cd /home/ubuntu/
#     npm run build

# - name: stop pm2
#   shell: |
#     cd /home/ubuntu/
#     pm2 stop default

# - name: Start backend with pm2
#   shell: |
#     cd /home/ubuntu/
#     export $(cat .env | xargs) && rails 

#     pm2 start npm -- start --update-env
    
# - name: print message
#   debug:
#     msg: "{{ execute_node.stdout_lines }}"
# - name: save your list of processes
#   shell: |
#     cd /home/ubuntu/
#     pm2 save  



